### ISSUE TITLE
UnsatisfiedLinkError no jzmq in java.library.path

### ISSUE THREAD

**Issue by joelkuiper** [lynaghk/zmq-async#1]
I'm trying to use the library as described but I keep getting 

UnsatisfiedLinkError no jzmq in java.library.path  java.lang.ClassLoader.loadLibrary (ClassLoader.java:1874)

I'm on ubuntu 12.04 (32-bit) and installed the zeromq3 libs from source and checked that they are indeed installed:

```
#  ldconfig -v | grep zmq  
libzmq.so.3 -> libzmq.so.3.0.0
```

Any thoughts on how to resolve this?

EDIT: manually building and adding 
  :dependencies [[org.zeromq/jzmq "2.2.3"]]

to project.clj and then exporting LD_LIBRARY_PATH=/usr/local/lib seems to do the trick

**Comment by lynaghk** [comment]
Right now the `project.clj` pulls in OS X 64 and Linux 64 native compiled bindings to ZeroMQ that I made from a checkout of jzmq.
You're having issues because you're on x32.
If all you are doing is adding the `org.zeromq/jzmq` dependency, though, then maybe they are shipping with a more complete set of native bindings, in which case I should drop the ones in this project and rely on jzmq directly.

@trevorbernard, any thoughts on what the best course of action would be?

**Comment by trevorbernard** [comment]
@lynaghk is correct. JZMQ has a java component and a native component. The problem you were having was that your app couldn't find libjzmq. You resolved it by manually building jzmq which installed the shared library in /usr/local/lib.

Currently jzmq, doesn't ship with native compiled bindings but I've been meaning to remove the option to even install the shared jzmq library and bundle them with the jar.

**Comment by lynaghk** [comment]
@trevorbernard You mean remove the option for a manual install, or remove the option of bundling precompiled bits with the JAR?

For what it's worth, I think the latter case is much more convenient for most developers and ops folks---as long as the native bits are in their own JARs and can thus be excluded by maven if desired.

What would be the best way to compile for the most common architectures and release JARs?
Can TravisCI do that?

**Comment by trevorbernard** [comment]
@lynaghk The latter. We are on the same page, I just phrased it awkwardly. I would release them as separate native jars.

> What would be the best way to compile for most architectures and release JARs?

I'm not sure but I'll either create Vagrant scripts to generate my target platforms or setup a jenkins environment. I haven't really spent much time thinking about it.

> Can TravisCI do that?

Unfortunately, not very well from my knowledge.

**Comment by lynaghk** [comment]
Ah, awesome. Let me know if there's anything I can do to help; I'd love to drop the homemade native JARs in favor of an official set.

I'll leave this issue open until it's resolved upstream and zmq-async can take advantage of it.

**Comment by halgari** [comment]
Is there a reason you can't use JeroMQ? https://github.com/zeromq/jeromq

**Comment by lynaghk** [comment]
When I get some time I'm going to look into splitting up the underlying transport so that the library can be used with ZeroMQ, JeroMQ, and (possibly) nanomsg.
On my personal timeline, that's at least a month out unless someone forces me into action by setting up some pairing sessions to work out the details.

**Comment by trevorbernard** [comment]
@halgari JeroMQ and JZMQ should be a drop in replacement for one another. You should be able to do something like this:

``` clj
{:dependencies
 [[org.zeromq/jeromq "0.3.1"]
  [com.keminglabs/zmq-async "0.1.0" :exclusions [com.keminglabs/jzmq]]]
}
```

If that doesn't work, I'd try the latest 0.3.2-SNAPSHOT. I remember having to modify Socket.bind and Socket.sendByteBuffer to use the same API as JZMQ.

**Comment by lynaghk** [comment]
Closing this until someone can confirm usage of Jero and/or take the lead on this issue. I don't have the bandwidth.
