### ISSUE TITLE
Port to cljzmq.

### ISSUE THREAD

**Issue by ToBeReplaced** [lynaghk/zmq-async#2]
What would you think about porting to use the zeromq provided clojure wrapper, [cljzmq](https://github.com/zeromq/cljzmq), as mentioned in the README?

This would eliminate a healthy amount of code and allow this library to focus exclusively on the problem it solves.

**Comment by lynaghk** [comment]
Can you be more specific about what this would accomplish?
What code that's in the library now could be replace with calls to cljzmq?

**Comment by ToBeReplaced** [comment]
You could remove `send!` and `receive-all!`.  You could remove the ZMQ part of `poll`, as well as the keyword dispatch on `:socket-type` in `register-socket!`.  Moreover, using the constructors in cljzmq for things like `ZContext` would help with future-proofing and prevent you from needing to deal with type hints.

**Comment by lynaghk** [comment]
The `send!` and `receive-all!` functions are basically private.
I can't justify adding a full dependency to drop those 20 straightforward lines.

The latest cljzmq code just has a light wrapper around the zmq poller that doesn't offer anything over the direct Java interop; the existing poller code in zmq-async would have to remain.

Re: future-proofing, the `:configurator` function gives consumers direct access to underlying jzmq socket and is thus future-proof already.
If the `ZContext` constructor changes in the future, I'll deal with it then = )

**Comment by ToBeReplaced** [comment]
Fair enough.  Just to add a final two cents, I think it's worth adding the dependency to give you less to support and make it easier to move towards byte buffers and the like.  It's awkward that someone is going to expect different semantics from your `send!` than they would expect from cljzmq's `send`.

**Comment by lynaghk** [comment]
No one should be using the `send!`; it's intentionally undocumented in the README, and using it defeats the purpose of this library (to use core.async channels rather than ZeroMQ sockets directly)  = )
