### ISSUE TITLE
I am a newbie, need your help please?

### ISSUE THREAD

**Issue by Ghassan** [lynaghk/zmq-async#7]
I am new to 0MQ so forgive possibly the naive question. Your help is warmly appreciated. Everything works until:

(require '[zmq-async.core :refer [context initialize! register-socket!]])

I get the exception:

java.io.FileNotFoundException: Could not locate zmq_async/core__init.class or zmq_async/core.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
RT.java:449 clojure.lang.RT.load
RT.java:412 clojure.lang.RT.load
core.clj:5866 clojure.core/load[fn]
core.clj:5865 clojure.core/load
RestFn.java:408 clojure.lang.RestFn.invoke
core.clj:5671 clojure.core/load-one
core.clj:5711 clojure.core/load-lib[fn]
core.clj:5710 clojure.core/load-lib
RestFn.java:142 clojure.lang.RestFn.applyTo
core.clj:632 clojure.core/apply
core.clj:5749 clojure.core/load-libs
RestFn.java:137 clojure.lang.RestFn.applyTo
core.clj:632 clojure.core/apply
core.clj:5832 clojure.core/require
RestFn.java:408 clojure.lang.RestFn.invoke
/Users/spaceshuttle/Documents/FP/Clojure/source_code/my-code/zmq-async-1/src/zmq_async_1/core.clj:41 zmq-async-1.core/eval10396
Compiler.java:6782 clojure.lang.Compiler.eval
Compiler.java:6745 clojure.lang.Compiler.eval
core.clj:3081 clojure.core/eval
eval.clj:77 lighttable.nrepl.eval/->result
core.clj:2493 clojure.core/partial[fn]
core.clj:2622 clojure.core/map[fn]
LazySeq.java:40 clojure.lang.LazySeq.sval
LazySeq.java:49 clojure.lang.LazySeq.seq
RT.java:507 clojure.lang.RT.seq
core.clj:137 clojure.core/seq
core.clj:2679 clojure.core/filter[fn]
LazySeq.java:40 clojure.lang.LazySeq.sval
LazySeq.java:49 clojure.lang.LazySeq.seq
RT.java:507 clojure.lang.RT.seq
core.clj:137 clojure.core/seq
core.clj:3009 clojure.core/dorun
core.clj:3025 clojure.core/doall
eval.clj:126 lighttable.nrepl.eval/eval-clj
RestFn.java:442 clojure.lang.RestFn.invoke
eval.clj:187 lighttable.nrepl.eval/eval2469[fn]
AFn.java:152 clojure.lang.AFn.applyToHelper
AFn.java:144 clojure.lang.AFn.applyTo
core.clj:630 clojure.core/apply
core.clj:1868 clojure.core/with-bindings*
RestFn.java:425 clojure.lang.RestFn.invoke
eval.clj:177 lighttable.nrepl.eval/eval2469[fn]
eval.clj:176 lighttable.nrepl.eval/eval2469[fn]
MultiFn.java:229 clojure.lang.MultiFn.invoke
core.clj:98 lighttable.nrepl.core/queued[fn]
core.clj:2437 clojure.core/comp[fn]
interruptible_eval.clj:138 clojure.tools.nrepl.middleware.interruptible-eval/run-next[fn]
AFn.java:22 clojure.lang.AFn.run
ThreadPoolExecutor.java:1142 java.util.concurrent.ThreadPoolExecutor.runWorker
ThreadPoolExecutor.java:617 java.util.concurrent.ThreadPoolExecutor$Worker.run
Thread.java:745 java.lang.Thread.run

**Comment by lynaghk** [comment]
Looks like you made a typo and forgot the first parts of the namespace. The require statement should be:

``` clojure
(require '[com.keminglabs.zmq-async.core :refer [context initialize! register-socket!]])
```

as in the README example.

cheers!

kevin
